# Machine Intelligence II - Team MensaNord
## Sheet 06

- Nikolai Zaki
- Alexander Moore
- Johannes Rieke
- Georg Hoelger
- Oliver Atanaszov

In [1]:
from __future__ import division, print_function
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np
%matplotlib inline
import scipy.io.wavfile
import scipy.stats
import numpy as np

## Exercise 1
### A

In [187]:
def E_s(W, s):
    for col in range(W.shape[0]):
        W[col, :] *= s[col]
        W[:, col] *= s[col]
    return - np.sum(W) / 2

# Test
A = np.array([[1, 2, 3], [1, 2, 3], [1, 2, 3]])
B = np.array([1, 0, 1])
print(E_s(A, B))

-4.0


In [188]:
# inintialization

t_max = 1000
M = 1

beta = np.random.random() / 50
print(1 / beta) # == Temperature

tau = np.random.random() + 2
print(tau)

s = np.random.choice([-1, 1], 6)
print(s)

W = np.random.random(size=(6, 6))
W = (W + W.T)/2
for i in range(W.shape[0]):
    W[i, i] = 0
print(W)

59.014769077438736
2.837116842538002
[ 1  1 -1  1 -1 -1]
[[ 0.          0.61103419  0.57568071  0.5739904   0.31838324  0.56268543]
 [ 0.61103419  0.          0.40357531  0.11779677  0.28455015  0.27143081]
 [ 0.57568071  0.40357531  0.          0.49606583  0.71460417  0.51276559]
 [ 0.5739904   0.11779677  0.49606583  0.          0.49661494  0.40062795]
 [ 0.31838324  0.28455015  0.71460417  0.49661494  0.          0.61741384]
 [ 0.56268543  0.27143081  0.51276559  0.40062795  0.61741384  0.        ]]


In [410]:
validation_min = E_s(W, s) # for validation
print(validation_min)
print("start")

for t in range(t_max):
    for m in range(M):        
        i = np.random.randint(0, 6)
        s_local = s
        s_local[i] *= -1
        E_1 = E_s(W, s)
        E_2 = E_s(W, s_local)
        E_d = E_2 - E_1
        P = 1 / (1 + np.exp(beta*E_d))
        if np.random.random() < P:
            s = s_local
        if E_s(W, s) < validation_min:
            validation_min = E_s(W, s)
    beta *= tau
print("s optimal", s)
print("E optimal", E_s(W, s))
print("min for reference", validation_min)
# ERROR validation_min has to be < E optimal

2.16017204373
start
s optimal [ 1  1  1  1  1 -1]
E optimal 0.118559821692
min for reference 2.16017204373


/home/georg/anaconda3/lib/python3.6/site-packages/ipykernel/__main__.py:13: RuntimeWarning: invalid value encountered in double_scalars
